### PR TITLE
ensure linter is actually available

### PR DESCRIPTION
**Pull request by Hades32**
BTW using https://golangci-lint.run/usage/install/#ci-installation might make sense in the future

### CODE REVIEW

**Comment by AmFlint** [comment]
Thank you I'll take a look at it this afternoon

**Comment by Hades32** [comment]
sorry, GitHub Actions seem to behave differently than local... I'll get this

**Comment by Hades32** [comment]
finally working consistently locally nad in CI

**Comment by AmFlint** [comment]
Thank you :) Unfortunately I did not have time to manage this part when I released this repository.

Merging this

**Pull request merged**
